# -*- coding: utf-8 -*-
"""Untitled2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1HUvilIVuW5PWhgd8PkWmKEVGK1wY5N9N
"""

#select operation in DataFrame
#access column data

import pandas as pd

employeedet = {'empid':[101,102,103,104,105],'ename':['Allen','Donald','Kelly','Pattrick','Williams'],'salary':[25000,30000,28000,23000,24000]}
emp_df=pd.DataFrame(employeedet)
print(emp_df)

print(emp_df.empid)

print(emp_df[['empid','salary']])





print(emp_df[['empid','salary']])

#how to add new column to dataframe

import pandas as pd

employeedet ={'empid':[101,102,103,104,105],'ename':['Allen','Donald','Kelly','Pattrick','Williams'],'esalary':[25000,30000,45000,40000,34000]}
emp_df = pd.DataFrame(employeedet)
#print(emp_df)
#adding new column to a dataframe
emp_df['joining_date']=['12-05-2018','01-07-2015','23-02-2016','1-04-2019','10-05-2015']
print(emp_df)

#select operation in DataFrame
#access column data

import pandas as pd

employeedet ={'empid':[101,102,103,104,105],'ename':['Allen','Donald','Kelly','Pattrick','Williams'],'esalary':[25000,30000,45000,40000,34000]}
emp_df = pd.DataFrame(employeedet)
print(emp_df)

#How to add new column to dataframe
import pandas as pd

employeedet ={'empid':[101,102,103,104,105],'ename':['Allen','Donald','Kelly','Pattrick','Williams'],'esalary':[25000,30000,45000,40000,34000]}
e_df = pd.DataFrame(employeedet)
#print(e_df)
e_df['Salary_with_bonus']=e_df['esalary']+e_df['esalary']*.05
print(e_df)

#how to rename the column
e_df.rename(columns = {"empid":"employee_ID"}, inplace=True)
print(e_df)

#how to drop a rows from a dataframe
#drop() : row-wise (axis=0)
e_df = e_df.drop(index=[2,3],axis=0)
print(e_df)

#how to drop a column from a dataframe
#drop() - column-wise (axis=1)
e_df = e_df.drop('Salary_with_bonus',axis=1)
print(e_df)

#how to drop a rows from a dataframe
#drop() : row-wise (axis=0)
'''
e_df = e_df.drop(index=[2,3],axis=0)
'''
e_df.reset_index(inplace=True)
print(e_df)

e_df
#top 2 records
#e_df.head(2)
e_df.tail(2)



#accessing data from dataframe using loc & iloc

#syntax : df.loc[startrow:EndRow, Startcolumn:EndColumn]
import pandas as pd

employeedet ={'empid':[101,102,103,104,105],'ename':['Allen','Donald','Kelly','Pattrick','Williams'],'esalary':[25000,30000,45000,40000,34000]}
e_df = pd.DataFrame(employeedet)
print(e_df.loc[2:3, : ])
print(e_df.loc[2:3, 'empid':'ename'])

#Simple line draw

import matplotlib.pyplot as plt
x=[1,2,3]
y=[2,3.5,5]
plt.plot(x,y)
plt.show()



#Simple Line draw
import matplotlib.pyplot as plt
x = [1,2,3]
y = [2,3.5,5]
plt.plot(x,y)
plt.show()

import matplotlib.pyplot as plt
x=[10,20,30,40,50]
y=[65,98,170,220,310]
plt.xlabel('Overs')
plt.ylabel('Runs Scored')
plt.title('Over wise Runs scored \n India Vs Australia')
plt.plot(x,y,'r',linewidth=5,linestyle='dotted')
plt.show()



import matplotlib.pyplot as plt
x=[10,20,30,40,50]
y=[65,98,170,220,310]
plt.xlabel('Overs')
plt.ylabel('Runs Scored')
plt.title('Over wise Runs scored \n India Vs Australia')
plt.plot(x,y,marker='*',markersize='15',markeredgecolor='red')
plt.show()

#Bar Graph Plotting

import matplotlib.pyplot as plt

OverRange=['1-10','11-20','21-30','31-40','41-50']
RunScored=[65,55,70,50,80]

plt.bar(OverRange,RunScored)
plt.xlabel('Over Intervals')
plt.ylabel('Runs Scored')
plt.show()

#change bar width & color
import matplotlib.pyplot as plt

OverRange=['1-10','11-20','21-30','31-40','41-50']
RunScored=[65,55,70,50,80]

plt.bar(OverRange,RunScored,width=0.3,color=['r','g','b','c','m'])
plt.xlabel('Over Intervals')
plt.ylabel('Runs Scored')
plt.show()

import matplotlib.pyplot as plt

OverRange=['1-10','11-20','21-30','31-40','41-50']
RunScored=[65,55,70,50,80]

plt.barh(OverRange,RunScored)
plt.xlabel('Over Intervals')
plt.ylabel('Runs Scored')
plt.show()



"""### **#Multiple Bars**"""

import matplotlib.pyplot as plt
import numpy as np

teamA=[50,60,70,80,90]
teamB=[55,65,60,75,96]

x=np.linspace(1,51,5)
plt.bar(x,teamA,width=3,color='g',label='Australia')
plt.bar(x+3,teamB,width=3,color='y',label='India')
plt.xlabel('Overs')
plt.ylabel('Runs Scored')
plt.title('Scoring Chart Australia vs India')
plt.legend()
plt.show()

import matplotlib.pyplot as plt
import numpy as np

teamA = [50,60,70,80,90]
teamB = [55,65,60,75,96]

x = np.linspace(1,51,5)
plt.bar(x,teamA,width=3,color='g',label='Australia')
plt.bar(x+3,teamB,width=3,color='yellow',label='India')
plt.xlabel('Overs')
plt.ylabel('Runs Scored')
plt.title('Scoring chart Australia Vs India')
plt.legend()
plt.show()